global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'telegram-bot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.67.184:8084']  # если запускаете локально